version: "3.0"

services:
    eduart-virtual-joy:
        image: eduartrobotik/eduart-virtual-joy:0.1.0
        container_name: eduart-virtual-joy-0.1.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
        network_mode: "host"
        command: bash -c 'ros2 run edu_virtual_joy virtual_joy --ros-args -r __ns:=${EDU_ROBOT_NAMESPACE}'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
